name: 'GitHub Actions validator'
description: 'Greet someone'

runs-on: ubuntu-latest
runs:
  using: "composite"
  steps:
    - run: pip install -qr ${{ github.action_path }}/requirements.in
      shell: bash
    - run: ${{ github.action_path }}/src/ga_actions_check_ref.py
      shell: bash
