name: "CI: Linters"

on:
  pull_request:

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: venv
        key: pip-v1-${{ hashFiles('dev-requirements.txt') }}
        restore-keys: |
          pip-v1-
    - name: Cache pre-commit
      uses: actions/cache@v2
      with:
        path: /tmp/pre-commit-cache
        key: pre-commit-v1-{{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-v1-
    - name: Install dependencies
      run: make sync
    - name: Run the pre-commit hooks
      run: make lint
      env:
        PRE_COMMIT_HOME: /tmp/pre-commit-cache
