name: "CI: Tests"

on:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: venv
        key: pip-v2-${{ hashFiles('dev-requirements.txt') }}
        restore-keys: |
          pip-v2-
    - name: Install dependencies
      run: make sync
    - name: Run the tests
      run: make tests
