name: "CI: Tests"

on:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: venv
        key: pip-v1-${{ hashFiles('dev-requirements.txt') }}
        restore-keys: |
          pip-v1-
    - name: Install dependencies
      run: make sync
    - name: Run the tests
      run: make tests
